# Site settings
title: Krishnan Chandra
email: me@krishnanchandra.com
description: "Krishnan's personal web site!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2c3e50
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Krishnan Chandra
  location: "San Francisco, CA"
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/krishnanchandra
  - title: bitbucket 
    url: http://bitbucket.org/kchandra
  - title: github
    url: http://github.com/krishnan-chandra
  - title: file-pdf-o
    url: Resume.pdf

# Credits content
credits: 'I built this website with the wonderful aid of <a href="http://startbootstrap.com/template-overviews/freelancer/">Freelancer</a>.'

# Build settings
markdown: kramdown
permalink: pretty
