# Example found at https://github.com/nishanths/cocoa-hugo-theme/blob/master/exampleSite/config.toml

baseURL             = "/"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Krishnan Chandra"
title               = "Krishnan's Personal Website"
disableKinds        = ["RSS"]

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[params]
lang                   = "en"
latestpostscount       = 10

# About the author
author                 = "Krishnan Chandra"
email                  = "me@krishnanchandra.com"
linkedin               = "//linkedin.com/in/krishnanchandra"
github                 = "//github.com/krishnan-chandra"
avatar                 = "/img/profile.png"

description            = "Krishnan's Home Page"

